# Generated by Django 4.2.2 on 2023-06-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='range',
            new_name='name',
        ),
    ]
